/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminSubmissionsRouteImport } from './routes/admin.submissions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminFoundersRouteImport } from './routes/admin.founders'
import { Route as AdminBlogsRouteImport } from './routes/admin.blogs'
import { Route as AdminAboutRouteImport } from './routes/admin.about'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFoundersRoute = AdminFoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAboutRoute = AdminAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/founders': typeof AdminFoundersRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/founders': typeof AdminFoundersRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/founders': typeof AdminFoundersRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/privacy'
    | '/projects'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/about'
    | '/admin/blogs'
    | '/admin/founders'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/testimonials'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/admin/'
    | '/blog/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/about'
    | '/admin/blogs'
    | '/admin/founders'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/testimonials'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/admin'
    | '/blog'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/privacy'
    | '/projects'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/about'
    | '/admin/blogs'
    | '/admin/founders'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/testimonials'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/admin/'
    | '/blog/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/founders': {
      id: '/admin/founders'
      path: '/founders'
      fullPath: '/admin/founders'
      preLoaderRoute: typeof AdminFoundersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/about': {
      id: '/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AdminAboutRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAboutRoute: typeof AdminAboutRoute
  AdminBlogsRoute: typeof AdminBlogsRoute
  AdminFoundersRoute: typeof AdminFoundersRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAboutRoute: AdminAboutRoute,
  AdminBlogsRoute: AdminBlogsRoute,
  AdminFoundersRoute: AdminFoundersRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
